### ISSUE TITLE
How is it different that just plotting points from position?

### ISSUE THREAD

**Issue by jesussmile** [ibrierley/line_animator#12]
Hi there,
before I stumbled onto this, i draw my own polyline like this 
```dart
 @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addPostFrameCallback((_) {});
  
    const factory = LocationMarkerDataStreamFactory();
    _geolocatorStream =
        factory.defaultPositionStreamSource().asBroadcastStream();
    _geolocatorStream.listen((position) {
      if (position != null) {
        setState(() {
          polyAirPlaneRoute.add(LatLng(position.latitude, position.longitude));
         
        });
      }
    });
  }
```
and simply add the polyAirPlaneRoute like this on my widget
```dart
IgnorePointer(
    child: PolylineLayer(
        polylines: [
            Polyline(
                points:
                polyAirPlaneRoute, //KTM_TMA, //VNKT_VNVT,
                isDotted: false,
                strokeWidth: 5,
                color: Colors.green,
                borderColor: Colors.white,
                borderStrokeWidth: 2,
                // borderColor: Colors.black45, //.withOpacity(0.5),
                //borderStrokeWidth: 2
                // gradientColors: gradientColors2,
            ),
        ],
    ),
),


```
gives me lines like this 
![Screenshot_20230628-182907](https://github.com/ibrierley/line_animator/assets/11044978/2145dcad-6c1d-4fca-9399-c172c2d0c8fb)

Just a simple question, respectfully, what is different about this  to the method above ? and how can it be helpful.

**Comment by ibrierley** [comment]
Simple questions are the best :D.

The main difference is that in the plugin, it takes an already existing route, and animates along it (interpolating all the inbetween points to make it smooth). Rather than build a new route from GPS like yours. 

Let's say you have a simple two point polyline from London to Paris, it will animate along that line for whatever time period you want (and reverse it if necessary and provide the angle of direction). So it will plot on every intermediate point that doesn't currently exist on the List of points.

**Comment by jesussmile** [comment]
okay! got you. needed this feature.
